version: "3.9"

services:
  # Database
  db:
    image: postgres:15
    container_name: mini-chat-db
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: mini_chat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend
  backend:
    build:
      context: ./backend
    container_name: mini-chat-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://chatuser:chatpass@db:5432/mini_chat
    depends_on:
      - db
    command: ["./start.sh"]   # ‚≠ê use start.sh instead of raw uvicorn command

  # Frontend
  frontend:
    build:
      context: ./frontend
    container_name: mini-chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      
volumes:
  pgdata:
